### ISSUE TITLE
Create a website design for our webpage

### ISSUE THREAD

**Issue by projectGroup3250Team2** [CS3250Team2/Campus-Navigator#4]
This issue will be designing the graphical layout whereas the implementation will be handled in the other issue thread.

**Comment by RyanHiller** [comment]
Since it's going to be a web app I feel we should use a front end framework that will allow for single-page development rather than making the user load different web pages to get to different features.

**Comment by projectGroup3250Team2** [comment]
Do you think this would speed up load times?

**Comment by RyanHiller** [comment]
Yeah having a single page app allows for a lot of the processing to be done on the frontend so unless a request has to be sent to the server the user's machine is doing the hard work which is beneficial to the wellbeing of the server and also means no requesting other pages from the server.

The main thing is that most modern frontend frameworks are state based so if you're not familiar with the concept of applicationates this part might be tough.

**Comment by projectGroup3250Team2** [comment]
Sounds like you might be the most ready to do this part would you like to?

**Comment by RyanHiller** [comment]
Yeah once we get the design down I'll have no issue implementing it that's fine with me.

**Comment by projectGroup3250Team2** [comment]
Im going to assign you to this issue and consider it in progress then :P

**Comment by RyanHiller** [comment]
I made issue #10 for the implementation and leave this issue specifically for the design aspect.

**Comment by projectGroup3250Team2** [comment]
So would you like someone to help you with the design look?

**Comment by projectGroup3250Team2** [comment]
https://www.awwwards.com/websites/clean/
